CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR2(20),
    
    
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID)
    );
CREATE SEQUENCE dept_seq START WITH 1;

CREATE OR REPLACE TRIGGER dept_bir 
BEFORE INSERT ON DEPARTMENT 
FOR EACH ROW

BEGIN
  SELECT dept_seq.NEXTVAL
  INTO   :new.DEPARTMENT_ID
  FROM   dual;
END;


CREATE TABLE EMPLOYEE(
    EM_ID NUMBER,
    EM_FNAME VARCHAR2(20),
    EM_LNAME VARCHAR2(20),
    DEPARTMENT_ID NUMBER,
    SALARY NUMBER,
    EM_EMAIL VARCHAR(20),
    
    CONSTRAINT EM_PK PRIMARY KEY (EM_ID),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
CREATE SEQUENCE em_seq START WITH 1;

CREATE OR REPLACE TRIGGER em_bir 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW

BEGIN
  SELECT em_seq.NEXTVAL
  INTO   :new.EM_ID
  FROM   dual;
END;

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('ACCOUNTING');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('ENGINEERING');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('SALES');


INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('Kunta','Jhonson',1,1000000000000000,'KJ@email');
/
INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('Hirihito','Jhan',1,20000,'HJ@email');
/
INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('Henrry','Lugosi',2,123456,'HL@email');
/
INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('N/A','Prince',2,689689,'Prince@email');
/
INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('Julian','Barbosa',3,20,'JB@email');
/
INSERT INTO EMPLOYEE (EM_FNAME,EM_LNAME,DEPARTMENT_ID,salary,em_email)
VALUES('Lilith','Wharmen',3,6621,'LW@email');
/

SELECT SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT
ON employee.department_id=department.department_id;